name: fuel_bills_app
description: Track fuel consumption and get reminded about credit card and utility bill due dates.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
